### ISSUE TITLE
File Path error for imports on windows

### ISSUE THREAD

**Issue by JohnLu2004** [CarletonComputerScienceSociety/questions#7]
![image](https://github.com/user-attachments/assets/863825d0-4094-48bd-aa38-83b6129fcb71)

**Comment by MrRibcage** [comment]
Fixed by [202500f](https://github.com/CarletonComputerScienceSociety/questions/commit/202500ffc8ccfa9b6622f7e36ef9ea645dab67de), generalized at [0c89070](https://github.com/commit/0c89070a00d015b8a3ec589c3a60dc3cac4757b4)
